# netlify.toml

[build]
  command   = "npm run build"
  publish   = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  command    = "npm run dev"
  targetPort = 3000
  port       = 8888
  autoLaunch = false

[build.processing]
  secrets_scan_enabled = false
